/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSchemesRouteImport } from './routes/_authenticated/app.schemes'
import { Route as AuthenticatedAppComplaintsRouteImport } from './routes/_authenticated/app.complaints'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'

const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSchemesRoute = AuthenticatedAppSchemesRouteImport.update({
  id: '/app/schemes',
  path: '/app/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppComplaintsRoute =
  AuthenticatedAppComplaintsRouteImport.update({
    id: '/app/complaints',
    path: '/app/complaints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/journeys': typeof JourneysRoute
  '/pitch': typeof PitchRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/complaints': typeof AuthenticatedAppComplaintsRoute
  '/app/schemes': typeof AuthenticatedAppSchemesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/journeys': typeof JourneysRoute
  '/pitch': typeof PitchRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/complaints': typeof AuthenticatedAppComplaintsRoute
  '/app/schemes': typeof AuthenticatedAppSchemesRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/journeys': typeof JourneysRoute
  '/pitch': typeof PitchRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/complaints': typeof AuthenticatedAppComplaintsRoute
  '/_authenticated/app/schemes': typeof AuthenticatedAppSchemesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/features'
    | '/journeys'
    | '/pitch'
    | '/app/chat'
    | '/app/complaints'
    | '/app/schemes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/features'
    | '/journeys'
    | '/pitch'
    | '/app/chat'
    | '/app/complaints'
    | '/app/schemes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/architecture'
    | '/auth'
    | '/features'
    | '/journeys'
    | '/pitch'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/complaints'
    | '/_authenticated/app/schemes'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  JourneysRoute: typeof JourneysRoute
  PitchRoute: typeof PitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/schemes': {
      id: '/_authenticated/app/schemes'
      path: '/app/schemes'
      fullPath: '/app/schemes'
      preLoaderRoute: typeof AuthenticatedAppSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/complaints': {
      id: '/_authenticated/app/complaints'
      path: '/app/complaints'
      fullPath: '/app/complaints'
      preLoaderRoute: typeof AuthenticatedAppComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppComplaintsRoute: typeof AuthenticatedAppComplaintsRoute
  AuthenticatedAppSchemesRoute: typeof AuthenticatedAppSchemesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppComplaintsRoute: AuthenticatedAppComplaintsRoute,
  AuthenticatedAppSchemesRoute: AuthenticatedAppSchemesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  JourneysRoute: JourneysRoute,
  PitchRoute: PitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
